<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Contato ID <?php echo $this->escapeHtml($contato->id); ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->escapeHtml($contato->nome); ?></dd>
            <dt>Telefone Principal:</dt>
            <dd><?php echo $this->escapeHtml($contato->telefone_principal); ?></dd>
            <dt>Telefone Secundario:</dt>
            <dd><?php echo $this->escapeHtml($contato->telefone_secundario); ?></dd>
            <dt>Data Criação:</dt>
            <dd><?php echo $this->escapeHtml($contato->data_criacao); ?></dd>
            <dt>Data Atualização:</dt>
            <dd><?php echo $this->escapeHtml($contato->data_atualizacao); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('contatos', array('action' => 'editar', 'id' => $contato->id)); ?>" class="btn btn-warning btn-sm">Editar Contato</a>
        <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>